Fushigi.Byml/BymlBigDataNode.cs
Fushigi.Byml/BymlWriter.cs
Fushigi.Byml/Utils.cs
Fushigi.Byml/Writer/BymlBigDataList.cs
Fushigi/Program.cs

This fixes the data not being seeked correctly when writing the data and also a casting error as it expects IBymlNode to have the value obtained by the "Data" property.. 
The default byml version is also now set to 7.

Fix byml writing big data types.

---

Fushigi/Program.cs
Fushigi/RomFS.cs
Fushigi/course/Course.cs
Fushigi/ui/widgets/AreaScene.cs

- CacheCourseFiles moved to RomFs.cs
- DoAreaScene moved and modularized in new AreaScene.cs
- Miscellaneous readability reformats (changing some for loops to foreach)
- Allows one course to be selected at a time, saving performance on creating Course objects for courses that aren't being displayed (significant improvement from when users had multiple courses selected)
- Fixes a crash that occurred when switching levels while the area map/actor list was opened

Clean Program.cs and add radio select courses

---

Fushigi/ui/MainWindow.cs

Allows for Windows do be docked to the edges of the Viewport and thus make better usage of the space

Enable Docking to Viewport

---

Fushigi/ui/MainWindow.cs

Makes save menus grayed out rather than not being visible when a course is loaded.

Adjust the menu to use disabled save text when course is not loaded

---

Fushigi/ui/MainWindow.cs
Fushigi/ui/widgets/CourseScene.cs
Fushigi/util/UserSettings.cs

- Course selection now opens up right away if the user has a romfs path set
- Added welcome message for those who do not have romfs path set
- Course selection goes away when course is selected
- Course selection can be opened with new File->Open Course button in main menu
- Actors get unselected when changing course areas
- Actor parameters is now always displayed, which is good for layout purposes
New open course button
Look at layout without course select, as well as the actor parameters displayed without a selected actor
Simple welcome message

Change Course Selection Flow

---

Fushigi/param/ParamDB.cs
Fushigi/util/FileUtil.cs

This pull request adds a quick check to the ParamDB.Load() method to make sure the file being loaded has the .zs extension.
This was a personal issue, but I thought it'd be good to make a PR to fix it incase anyone else runs into the same issue I did.

Extension checking in ParamDB Load

---

Fushigi/course/Course.cs
Fushigi/ui/MainWindow.cs
Fushigi/ui/widgets/CourseScene.cs
Fushigi/util/UserSettings.cs

- Implement and leverage UserSettings.RecentCourses to load the latest selected course on application startup
- This means UserSettings.RecentCourses is now being kept track of, so feel free to use it for anything else you may need
- Fix bug where viewport was not updating on tab switch
- Cleaned up CourseScene.cs unused fields after the LevelViewport transition

Load latest selected course on startup

---

Fushigi/ui/MainWindow.cs
Fushigi/ui/widgets/PathSelector.cs
Fushigi/ui/widgets/Tooltip.cs

When the user first loads the tool, it will prompt to select both the game romfs and a save  folder where edits are saved to. 
This also includes a PathSelector widget which can be reused for the settings window whenever that is made.

Add startup menu for selecting the romfs and mod folders.

---

Fushigi/ui/MainWindow.cs

When the ability to open up latest levels from UserSettings was added, it would render the CourseScene on frame 1, which was before ImGui settings were available (frame 3)
Now I moved the LoadFromSettings() call to be together with the ImGui.LoadIniSettingsFromDisk, so all the loading happens in one spot, and added a condition to the rendering so that it only renders levels frame 3 and beyond

Fix undocking bug

---

Fushigi/course/CourseArea.cs
Fushigi/rstb/RSTB.cs
Fushigi/ui/widgets/CourseScene.cs
Fushigi/util/Crc32.cs

Adds support for RSTB loading/saving and editing the table. Currently each area .byml is saved with the RSTB values updated. Can confirm this works in game and fixes the level from not loading when the file size gets larger than original size.
The calculation is confirmed to match the original resource size where it is rounded to nearest 32, then adds 0x100 to the size.
A few other extensions with confirmed calculation sizes are added such as .pack for future purposes if we decide to ever edit those files.

Add support for RSTB updating.

---

Fushigi/ui/widgets/CourseScene.cs
Fushigi/ui/widgets/LevelViewport.cs

When an actor is double clicked in the list, it will frame the camera to that selected actor.
The selection view is also updated in the viewport when an actor is selected in the list.

Support actor framing by camera and view selection in viewport

---

Fushigi/Fushigi.csproj
Fushigi/gl/GLImageCache.cs
Fushigi/gl/GLTexture.cs
Fushigi/gl/GLTexture2D.cs
Fushigi/ui/widgets/CourseScene.cs

As the current build, there is no way to load images intuitively so I added in support using some classes. 
There is static functions in GLTexture2D.Load() to simply load either an image file like .png, jpg, etc and also ones to load a raw image given the width, height and raw rgba8 data. 
This also includes a GLImageCache class, which can be used for loading in stored images from a lookup and can be easily disposed of. 
Once a GLTexture2D is created, simply access the ID property and use that to use with Imgui.Image() or use it to bind for gl rendering.

Add simple texture loading support

---

Fushigi/course/CourseArea.cs
Fushigi/ui/Transform.cs
Fushigi/ui/bgunit/UnitRailPointUndo.cs
Fushigi/ui/bgunit/UnitRailRenderer.cs
Fushigi/ui/undo/IRevertable.cs
Fushigi/ui/undo/TransformUndo.cs
Fushigi/ui/undo/UndoRedo.cs
Fushigi/ui/widgets/LevelViewport.cs

This is initial support for creating and editing wall rails. 
Walls are now stored under a list of WallUnitRenderers in CourseArea. These control all functionality for editing the wall units.
Beltrails have a similar treatment but I decided to hide them for now. I am not sure how we should handle these yet.
This also adds support for undo/redo handling by using CTRL + Z and CTRL + R for redo. 
Simply creating a IRevertable state, then adding to AddToUndo in the viewport to use. I currently have both transform, add, and delete states for the points for an idea on how I added this. This also includes a begin/end undo states for doing collection of states at once.

Add support for creating and editing terrain wall units.

---

Fushigi/ui/widgets/Preferences.cs

Add guard clause that stops RomFS.SetRoot and ParamDB.Load to run if the inputted romfs path is wrong. This was causing a crash for new users setting a bad path, would crash on ParamDB.Load trying to read a file from the romfs path that wasn't there.

Fix crash on setting wrong RomFS path

---

.github/workflows/dotnet.yml
.gitignore
Fushigi/Fushigi.csproj
Fushigi/course/CourseArea.cs
Fushigi/util/FileUtil.cs

- ZstdNet was switched for ZstdSharp.Port
- Added .idea for the gitignore
- Added options to build for Mac x64 and Arm to the workflows.

Switch to ZstdSharp and Mac Build options

---

Fushigi/ui/widgets/CourseScene.cs

(Edit)I forgot to change the actor also in the viewport and I added that the camera goes to the new selected Actor, Small but important change, so if you go through the links of an actor and you want to go to an linked actor you just need to click
on the button with their actor name and you auto select it

Added so that if you press the button of a link destination so that you auto select the linked Actor

---

Fushigi/ui/widgets/LevelViewport.cs

This should improve the general UX of Fushigi's viewport panning. The previous panning used Alt + LMB as a second gesture, however this caused some issues because the gesture was also being used for adding wall points.
Shift is a bigger key than Alt, it's easier to manage with your hands, and also, I can't use Space as a key (thanks Silk.Net ImGui mappings)

Replace Alt + LMB pan gesture with Shift + LMB.

---

Fushigi/ui/widgets/LevelViewport.cs
Fushigi/ui/widgets/UndoWindow.cs

Clicking actions in the History will revert to when that action took place, includes a "Course Loaded" action to easily undo all changes
Also actor boxes now only display their corner points when selected.

Undo History and Actor Box Points

---

Fushigi/ui/widgets/LevelViewport.cs

- 0.25 speed was painfully slow when zoomed out
- this preserves existing speed around the default+max zoom and speeds up in 0.25 increments every 10 distance, felt good to me
- real speed is (still) fps dependent, notice the higher speed at the end of this clip as there's less to render
- distance + speed are peeking out at the very bottom of this scuffed clip
https://github.com/shibbo/Fushigi/assets/137466401/90eaebbe-3c15-4725-8ea3-fe6a07e99cdf

Scale WASD panning speed with zoom

---

Fushigi/RomFS.cs
Fushigi/ui/MainWindow.cs
Fushigi/ui/widgets/CourseSelect.cs
Fushigi/ui/widgets/Preferences.cs

- Thumbnail loading done on romfs path set
- Better choice now that texture loading is done in the background
- Does not add significant time to start up (0.3s - 1s at most)
- No more hanging on world select, improved performance
- Thumbnails are likely fully loaded by the time the user opens course select, but will just be black rectangles until then
- Fix romfs path tampering crash
- There was a crash that would occur if a user tampered with their romfs path outside of the program and had opened a course before
- Certain things like the paramDB and latestCourse will now only load if the romfs path is valid
- If the saved romfs path is no longer valid on startup, the preferences window will be open so the user can reset it

Improve Course Select Loading

---

Fushigi/ui/widgets/LevelViewport.cs

The areaScene objects Draw2D was being called once per tile unit selected. This caused a bug where alt clicking would place multiple rail points in the same spot instead of just one. It was probably causing even more issues. This code was removed from the foreach loop it was in, and is now called once per frame as intended, and everything works great.

Fix adding multiple rail points on click

---

Fushigi/ui/widgets/LevelViewport.cs

the drain pipe refs need to be specified for it to work now, not just be present ('cuz middle pipes have it, but don't use it)

middle pipe fix

---

Fushigi/course/CourseActor.cs
Fushigi/env/EnvPalette.cs
Fushigi/gl/Bfres/BfresRender.cs
Fushigi/gl/Bfres/TileBfresRenderer.cs
Fushigi/ui/CourseAreaEditContext.cs
Fushigi/ui/widgets/CourseScene.cs
Fushigi/ui/widgets/LevelViewport.cs

Rendering & Link Fixes,
MiniMap Color Tweaks
Wonder View Modes Added

Fixes, MiniMap Tweaks, & Wonder View

---

Fushigi/actor_pack/ActorPack.cs
Fushigi/course/Course.cs
Fushigi/course/CourseRail.cs
Fushigi/course/distance_view/DistantViewManager.cs
Fushigi/param/ParamDB.cs
Fushigi/ui/EditContextBase.cs
Fushigi/ui/widgets/CourseScene.cs
Fushigi/ui/widgets/LevelViewport.cs
Fushigi/ui/widgets/PathSelector.cs
Fushigi/util/BymlUtil.cs

* Curved Rails can be created and their curve control point can be moved in the viewport when a point is selected.
* Overlapping rail points is possible now
* ***Adding layers is now possible*** (limits to the amount of Play/DecoArea layers)
* **WIP** Deleting Layers
* Fixed crash with loading bone params
* Fixed how Actor To Rail Links are saved, as the previous method caused bugs with objects that moved along them automatically.
* Legacy ImGui Column code rewritten with the newer API's ImGui Table code.
* Tweaked the UI of Actor to Rail Link and Local Links window
* Fixed selecting Tile Units, Rails, and Global Links via the UI windows
* Fixed batch undo when deleting multiple objects

Old Code Revamp, Curved Rails, & Actor To Rail Fix
